gridWorkingDir:		workingdir
gridOutputDir:		outputdir_13d_test_latest
aliROOTVersion:		v5-09-11-1
aliPhysicsVersion:	v5-09-11-01-1
gridDataDir:		/alice/data/2013/LHC13d
dataPattern:		/pass4/*/AliESDs.root
runPrefix:              000
runNumber:		[195783]
emcalCorrection:	emcal_correction_13d.yaml
