gridWorkingDir:		workingdir
gridOutputDir:		outputdir
aliROOTVersion:		v5-09-29-1
aliPhysicsVersion:	v5-09-29-01-1
package:		fastjet::v3.2.1_1.024-alice3-2
package:		cgal::v4.6.3-25
package:		boost::v1.59.0-19
package:		MPFR::v3.1.3-4
package:		GMP::v6.0.0-2
package:		GCC-Toolchain::v4.9.3-alice3-1
gridDataDir:		/alice/data/2016/LHC16k
dataPattern:		/pass1/*/AliESDs.root
runPrefix:		000
runNumber:		[258537]
emcalCorrection:	emcal_correction_notrkhist.yaml
emcalGeometryFilename:	geometry_2015.root
emcalLocal2MasterFilename: EMCALlocal2master.root
skimClusterMinE:        8
splitMaxInputFileNumber: 5
