gridWorkingDir:         workingdir_a1_4
gridOutputDir:          outputdir_a1_4
aliROOTVersion:         v5-09-29-1
aliPhysicsVersion:      v5-09-29-01-1
package:                fastjet::v3.2.1_1.024-alice3-2
package:                cgal::v4.6.3-25
package:                boost::v1.59.0-19
package:                MPFR::v3.1.3-4
package:                GMP::v6.0.0-2
package:                GCC-Toolchain::v4.9.3-alice3-1
gridDataDir:            /alice/sim/2017/LHC17i3a1/4
dataPattern:            */*/AliESDs.root
runNumber:              [256504, 256506, 256510, 256512, 256554, 256556, 256560, 256561, 256562, 256564, 256565, 256567, 256589, 256591, 256592, 256619, 256620, 256658, 256676, 256677, 256681, 256684, 256691, 256692, 256694, 256695, 256697, 256942, 256944, 257011, 257021, 257077, 257080, 257082, 257084, 257092, 257100, 257136, 257138, 257139, 257140, 257141, 257142, 257144, 257145, 257204, 257206, 257209, 257260, 257474, 257487, 257490, 257491, 257492, 257530, 257531, 257540, 257541, 257560, 257561, 257562, 257566, 257587, 257590, 257605, 257606, 257642, 257682, 257687, 257689, 257697, 257724, 257733, 257735, 257737, 257754, 257765, 257773, 257797, 257798, 257799, 257800, 257803, 257850, 257892, 257893, 257936, 257937, 257939, 257957, 257958, 257960, 258012]
runPrefix:
emcalCorrection:	emcal_correction_notrkhist.yaml
emcalGeometryFilename:	geometry_2015.root
emcalLocal2MasterFilename: EMCALlocal2master.root
